// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO9K9ck8L4jLfH9iKp7TL6Je5MqauUMZE',
    appId: '1:116061540313:web:6bd15931b0dc14a8bf13c8',
    messagingSenderId: '116061540313',
    projectId: 'scilearn-27bc8',
    authDomain: 'scilearn-27bc8.firebaseapp.com',
    storageBucket: 'scilearn-27bc8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFU1N_-3gvcHrNSqhu7CDI9aDZyXQgDo',
    appId: '1:116061540313:android:5e125116317cf464bf13c8',
    messagingSenderId: '116061540313',
    projectId: 'scilearn-27bc8',
    storageBucket: 'scilearn-27bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8-y2vPdUhcPGVV5CwXPUiyMIGGOr0OZA',
    appId: '1:116061540313:ios:e352aa3c7b42e0f0bf13c8',
    messagingSenderId: '116061540313',
    projectId: 'scilearn-27bc8',
    storageBucket: 'scilearn-27bc8.firebasestorage.app',
    iosBundleId: 'com.example.elearningappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8-y2vPdUhcPGVV5CwXPUiyMIGGOr0OZA',
    appId: '1:116061540313:ios:e352aa3c7b42e0f0bf13c8',
    messagingSenderId: '116061540313',
    projectId: 'scilearn-27bc8',
    storageBucket: 'scilearn-27bc8.firebasestorage.app',
    iosBundleId: 'com.example.elearningappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO9K9ck8L4jLfH9iKp7TL6Je5MqauUMZE',
    appId: '1:116061540313:web:2b8db8d207244e25bf13c8',
    messagingSenderId: '116061540313',
    projectId: 'scilearn-27bc8',
    authDomain: 'scilearn-27bc8.firebaseapp.com',
    storageBucket: 'scilearn-27bc8.firebasestorage.app',
  );
}
