// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaWJpw65V4qYgzr3uFO5Xe_8JZIzSM-Rs',
    appId: '1:329819554180:web:ac62ec949d6661658d9dd1',
    messagingSenderId: '329819554180',
    projectId: 'elearningapp-678e1',
    authDomain: 'elearningapp-678e1.firebaseapp.com',
    storageBucket: 'elearningapp-678e1.firebasestorage.app',
    measurementId: 'G-M6KJLH67DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAOtZe7TXWdalPfLEUB-1UN6Tu3kCNixA',
    appId: '1:329819554180:android:76b504426b7554428d9dd1',
    messagingSenderId: '329819554180',
    projectId: 'elearningapp-678e1',
    storageBucket: 'elearningapp-678e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84V-1V2x58fk_qFimH3wiIQ_SEYHJK2g',
    appId: '1:329819554180:ios:f23b3b81d8b37f258d9dd1',
    messagingSenderId: '329819554180',
    projectId: 'elearningapp-678e1',
    storageBucket: 'elearningapp-678e1.firebasestorage.app',
    iosBundleId: 'com.example.elearningappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA84V-1V2x58fk_qFimH3wiIQ_SEYHJK2g',
    appId: '1:329819554180:ios:f23b3b81d8b37f258d9dd1',
    messagingSenderId: '329819554180',
    projectId: 'elearningapp-678e1',
    storageBucket: 'elearningapp-678e1.firebasestorage.app',
    iosBundleId: 'com.example.elearningappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaWJpw65V4qYgzr3uFO5Xe_8JZIzSM-Rs',
    appId: '1:329819554180:web:77a0a176d19f748c8d9dd1',
    messagingSenderId: '329819554180',
    projectId: 'elearningapp-678e1',
    authDomain: 'elearningapp-678e1.firebaseapp.com',
    storageBucket: 'elearningapp-678e1.firebasestorage.app',
    measurementId: 'G-3EY1HGZHW7',
  );
}
